### PR TITLE
Implement local-only printing

### PR DESCRIPTION
**Pull request by jacobmarble**
In the config file, disable cloud printing with: `"cloud_printing_enable": false,`

Config file is no longer needed; default values will be used instead. Default value changes:
- disable cloud printing
- enable local printing
- move the monitor socket to /tmp
- enable SNMP

The idea here is to make SOHO situations easier to setup. Flaky, slow, privacy-sensitive and non-existent Internet gateways are accounted for this way.

### CODE REVIEW

**Comment by jay0lee** [comment]
Would prefer to see cloud printing enabled OOB rather than requiring it be turned on manually. Just my 2 cents.

**Comment by jacobmarble** [comment]
@jay0lee That's impossible because cloud requires an OAuth token. The old way, `connector-init`, still works; config files are still read when present.

**Comment by jay0lee** [comment]
@jacobmarble I see so then default value when no config file specified is no cloud print but default value assigned in a generated config file will still be to have cloud print enabled. If that's the new behavior, sgtm.

**Comment by jacobmarble** [comment]
No config file: local: true, cloud: false
`connector-init` asks the user yes/no for both local and cloud.

**Pull request merged**
