### PR TITLE
Add local printing

### PR DESCRIPTION
**Pull request by jacobmarble**
This (admittedly huge) change adds Privet to the connector, making progress on #6

### CODE REVIEW

**Comment by bvsbvs** [comment]
mostly lgtm, with some optional comments
feel free to merge if you think they are not worth of addressing.

**Comment by jacobmarble** [comment]
@bvsbvs Thank you for reviewing.

**Comment by RayBa82** [comment]
Now the compile Fails with go 1.5 and 1.4.2

go get github.com/google/cups-connector/connector

Yesterday it worked without problems

# github.com/google/cups-connector/privet
In file included from go/src/github.com/google/cups-connector/privet/avahi.go:12:0:
avahi.h:9:34: fatal error: avahi-client/publish.h: No such file or directory
 #include <avahi-client/publish.h>
                                  ^
compilation terminated.

**Comment by mceachen** [comment]
@RayBa82, see
https://github.com/google/cups-connector/issues/44#issuecomment-133597386

**Pull request merged**
